// GENERATED FILE — do not edit by hand.
//
//   python3 tools/build-poems.py /home/todd/Repos/tce284-fa26
//
// Source: tce284-fa26 @ c9f02df
// Built:  2026-08-23
// 16 poems across 27 class sessions.
// 3 carry their text (see poem-texts/README.md);
// the rest link out, which is what the course pages do.
// Sessions with no Daily Poem: week 1 Mon, week 7 Mon, week 9 Wed, week 11 Mon, week 11 Wed, week 12 Mon, week 12 Wed, week 13 Mon, week 13 Wed, week 15 Mon, week 15 Wed.
//
// Poem text, where present, is transcribed by hand into poem-texts/ and is there only
// when reproducing it is safe. This repo is public; adding a poem here republishes it.
window.DAILY_POEMS = [
  {"date": "2026-08-26", "week": 1, "day": "Wed", "src": "week-01-trust-the-gush/week-01-wed.html", "slug": "we-wear-the-mask", "title": "We Wear the Mask", "poet": "Paul Laurence Dunbar", "url": "https://www.poetryfoundation.org/poems/44203/we-wear-the-mask", "where": "", "note": "Dayton, Ohio", "text": "", "textSource": "", "framing": ["Read it aloud.", "What do you notice — the sounds, the repeated lines, the \"we\"? Who is the \"we\"? What is the mask, and who is it for?", "Where have you worn one — as a student, as a future teacher? What does the mask cost, and what does it protect?"]},
  {"date": "2026-08-31", "week": 2, "day": "Mon", "src": "week-02-writing-place/week-02-mon.html", "slug": "where-i-m-from", "title": "Where I'm From", "poet": "George Ella Lyon", "url": "http://www.georgeellalyon.com/where.html", "where": "", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. What do you notice — the lists, the specific names, the foods and sayings?", "The poem is built to be borrowed. Where are <em>you</em> from? Jot a few of your own lines — the objects, smells, and sayings only your place had."]},
  {"date": "2026-09-02", "week": 2, "day": "Wed", "src": "week-02-writing-place/week-02-wed.html", "slug": "i-dwell-in-possibility", "title": "I dwell in Possibility", "poet": "Emily Dickinson", "url": "https://www.poetryfoundation.org/poems/52197/i-dwell-in-possibility-466", "where": "", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. She calls poetry a house — \"A fairer House than Prose – / More numerous of Windows –.\" What kind of house is your writing?"]},
  {"date": "2026-09-09", "week": 3, "day": "Wed", "src": "week-03-voice-print/week-03-wed.html", "slug": "the-voice", "title": "The Voice", "poet": "Thomas Hardy", "url": "https://www.poetryfoundation.org/poems/52333/the-voice-56d230b56eb7c", "where": "", "note": "", "text": "", "textSource": "", "framing": ["— \"Woman much missed, how you call to me, call to me.\" Read it aloud. Whose voice is calling, and how does Hardy make you hear it across time? Where does he start to wonder whether it's really her, or only the wind?"]},
  {"date": "2026-09-14", "week": 4, "day": "Mon", "src": "week-04-show-dont-tell/week-04-mon.html", "slug": "blackberry-eating", "title": "Blackberry Eating", "poet": "Galway Kinnell", "url": "https://www.poetryfoundation.org/poems/42596/blackberry-eating", "where": "", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. Which words make you <em>taste</em> it — \"the black art of blackberry-making,\" the lumpy words he loves to \"squeeze, squinch open, and splurge\"? Point to the exact ones."]},
  {"date": "2026-09-16", "week": 4, "day": "Wed", "src": "week-04-show-dont-tell/week-04-wed.html", "slug": "mid-term-break", "title": "Mid-Term Break", "poet": "Seamus Heaney", "url": "", "where": "Canvas", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. Heaney never says he's grieving — he shows it: the knelling bells, the baby cooing, the old men standing to shake his hand, and the last line. Where does the grief land, and how does he get it there without naming it?"]},
  {"date": "2026-09-21", "week": 5, "day": "Mon", "src": "week-05-breaking-the-rules/week-05-mon.html", "slug": "short-order-cook", "title": "Short Order Cook", "poet": "Jim Daniels", "url": "https://poets.org/poem/short-order-cook", "where": "", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. Where does the poem move fast, break, and refuse to sit still? What rules is it not following — and why does it work?"]},
  {"date": "2026-09-23", "week": 5, "day": "Wed", "src": "week-05-breaking-the-rules/week-05-wed.html", "slug": "o-me-o-life", "title": "O Me! O Life!", "poet": "Walt Whitman", "url": "https://www.poetryfoundation.org/poems/51568/o-me-o-life", "where": "", "note": "", "text": "O me! O life! of the questions of these recurring,\nOf the endless trains of the faithless, of cities fill’d with the foolish,\nOf myself forever reproaching myself, (for who more foolish than I, and who more faithless?)\nOf eyes that vainly crave the light, of the objects mean, of the struggle ever renew’d,\nOf the poor results of all, of the plodding and sordid crowds I see around me,\nOf the empty and useless years of the rest, with the rest me intertwined,\nThe question, O me! so sad, recurring—What good amid these, O me, O life?\n\nAnswer.\n\nThat you are here—that life exists and identity,\nThat the powerful play goes on, and you may contribute a verse.", "textSource": "Walt Whitman, Leaves of Grass, Project Gutenberg ebook 1322", "framing": ["Read it aloud. After all the doubt and the \"empty and useless years,\" Whitman's answer: <em>\"that the powerful play goes on, and you may contribute a verse.\"</em> On the last day of Act I — after the machine flattened your words — what is the verse that only you can add?"]},
  {"date": "2026-09-28", "week": 6, "day": "Mon", "src": "week-06-what-is-currere/week-06-mon.html", "slug": "ethics", "title": "Ethics", "poet": "Linda Pastan", "url": "https://www.poetrynook.com/poem/ethics", "where": "", "note": "", "text": "", "textSource": "", "framing": ["— read it aloud (or hear Pastan read it herself). Her speaker was asked a question in school she couldn't really answer, and only understood it years later, standing in a museum as an old woman herself.", "Don't get stuck on \"ethics class.\" When has the meaning of something a teacher asked or said only caught up with you <em>later</em>?"]},
  {"date": "2026-09-30", "week": 6, "day": "Wed", "src": "week-06-what-is-currere/week-06-wed.html", "slug": "tell-all-the-truth-but-tell-it-slant", "title": "Tell all the truth but tell it slant", "poet": "Emily Dickinson", "url": "https://www.poetryfoundation.org/poems/56824/tell-all-the-truth-but-tell-it-slant-1263", "where": "", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. What does she mean by telling the truth \"slant\" instead of straight out? When have you told something true by coming at it sideways?"]},
  {"date": "2026-10-07", "week": 7, "day": "Wed", "src": "week-07-regressive-the-scene/week-07-wed.html", "slug": "those-winter-sundays", "title": "Those Winter Sundays", "poet": "Robert Hayden", "url": "https://www.poetryfoundation.org/poems/46461/those-winter-sundays", "where": "", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. A small remembered scene, and the meaning arrives only at the end — <em>\"What did I know, what did I know of love's austere and lonely offices?\"</em> How does one scene carry a whole relationship?"]},
  {"date": "2026-10-12", "week": 8, "day": "Mon", "src": "week-08-dramatize-and-break-rules/week-08-mon.html", "slug": "the-gift", "title": "The Gift", "poet": "Li-Young Lee", "url": "https://www.poetryfoundation.org/poems/43010/the-gift-56d221adc12b8", "where": "", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. One remembered moment — a father pulling a splinter — carries a whole life of tenderness. Where does the poem <em>show</em> instead of tell? Notice how it moves between past and present without ever announcing the years."]},
  {"date": "2026-10-14", "week": 8, "day": "Wed", "src": "week-08-dramatize-and-break-rules/week-08-wed.html", "slug": "since-feeling-is-first", "title": "[since feeling is first]", "poet": "E. E. Cummings", "url": "https://poets.org/poem/feeling-first", "where": "", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. Watch what he does to grammar on purpose — no capitals, the syntax bent to the feeling: <em>\"who pays any attention / to the syntax of things / will never wholly kiss you.\"</em> When does breaking the rule tell it truer than the rule would?"]},
  {"date": "2026-10-19", "week": 9, "day": "Mon", "src": "week-09-metaphor-and-leads/week-09-mon.html", "slug": "metaphors", "title": "Metaphors", "poet": "Sylvia Plath", "url": "https://www.poetryverse.com/sylvia-plath-poems/metaphors", "where": "", "note": "", "text": "", "textSource": "", "framing": ["Read it aloud. The whole poem is a riddle built <em>only</em> of images — \"an elephant, a ponderous house,\" \"a melon strolling on two tendrils\" — and she never says the plain word. What does saying it in metaphor do that the plain word couldn't?"]},
  {"date": "2026-10-26", "week": 10, "day": "Mon", "src": "week-10-mentors-and-the-hinge/week-10-mon.html", "slug": "the-road-not-taken", "title": "The Road Not Taken", "poet": "Robert Frost", "url": "https://www.poetryfoundation.org/poems/44272/the-road-not-taken", "where": "", "note": "", "text": "Two roads diverged in a yellow wood,\nAnd sorry I could not travel both\nAnd be one traveler, long I stood\nAnd looked down one as far as I could\nTo where it bent in the undergrowth;\n\nThen took the other, as just as fair,\nAnd having perhaps the better claim,\nBecause it was grassy and wanted wear;\nThough as for that the passing there\nHad worn them really about the same,\n\nAnd both that morning equally lay\nIn leaves no step had trodden black.\nOh, I kept the first for another day!\nYet knowing how way leads on to way,\nI doubted if I should ever come back.\n\nI shall be telling this with a sigh\nSomewhere ages and ages hence:\nTwo roads diverged in a wood, and I—\nI took the one less traveled by,\nAnd that has made all the difference.", "textSource": "Robert Frost, Mountain Interval, Project Gutenberg ebook 29345", "framing": ["Read it aloud. Notice the speaker isn't in the woods — he's <em>looking back</em>, \"ages and ages hence,\" making a story out of a choice: <em>\"I shall be telling this with a sigh.\"</em> How does meaning get made only in the looking-back?"]},
  {"date": "2026-10-28", "week": 10, "day": "Wed", "src": "week-10-mentors-and-the-hinge/week-10-wed.html", "slug": "song-of-myself-51", "title": "Song of Myself, 51", "poet": "Walt Whitman", "url": "https://poets.org/poem/song-myself-51", "where": "", "note": "", "text": "The past and present wilt—I have fill’d them, emptied them.\nAnd proceed to fill my next fold of the future.\n\nListener up there! what have you to confide to me?\nLook in my face while I snuff the sidle of evening,\n(Talk honestly, no one else hears you, and I stay only a minute longer.)\n\nDo I contradict myself?\nVery well then I contradict myself,\n(I am large, I contain multitudes.)\n\nI concentrate toward them that are nigh, I wait on the door-slab.\n\nWho has done his day’s work? who will soonest be through with his supper?\nWho wishes to walk with me?\n\nWill you speak before I am gone? will you prove already too late?", "textSource": "Walt Whitman, Leaves of Grass, Project Gutenberg ebook 1322, section 51", "framing": ["Read it aloud — it was built to be. <em>\"Do I contradict myself? / Very well then I contradict myself, / (I am large, I contain multitudes.)\"</em> Your one currere is one voice — but how many kinds of writing are packed inside it?"]}
];
