// GENERATED FILE — do not edit by hand.
//   python3 tools/build-readings.py /home/todd/Repos/tce284-fa26
// 37 readings: 26 Romano, 8 currere, 3 articles.
window.COURSE_READINGS = [
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154867",
  "title": "Intro",
  "file": "ch0-introduction.pdf",
  "ch": 0,
  "week": 1,
  "day": "Wed",
  "due": "2026-08-26",
  "dueLabel": "Wed, Aug 26",
  "outline": "week-01-trust-the-gush/week-01-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154842",
  "title": "ch1",
  "file": "ch1-who-are-you-to-presume-to-write.pdf",
  "ch": 1,
  "week": 1,
  "day": "Wed",
  "due": "2026-08-26",
  "dueLabel": "Wed, Aug 26",
  "outline": "week-01-trust-the-gush/week-01-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154853",
  "title": "ch2",
  "file": "ch2-trust-the-gush.pdf",
  "ch": 2,
  "week": 1,
  "day": "Wed",
  "due": "2026-08-26",
  "dueLabel": "Wed, Aug 26",
  "outline": "week-01-trust-the-gush/week-01-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154860",
  "title": "ch3",
  "file": "ch3-notebook-playground-repository.pdf",
  "ch": 3,
  "week": 2,
  "day": "Mon",
  "due": "2026-08-31",
  "dueLabel": "Mon, Aug 31",
  "outline": "week-02-writing-place/week-02-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154861",
  "title": "ch4",
  "file": "ch4-notebook-as-therapy.pdf",
  "ch": 4,
  "week": 2,
  "day": "Mon",
  "due": "2026-08-31",
  "dueLabel": "Mon, Aug 31",
  "outline": "week-02-writing-place/week-02-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154862",
  "title": "ch5",
  "file": "ch5-a-writing-place.pdf",
  "ch": 5,
  "week": 2,
  "day": "Wed",
  "due": "2026-09-02",
  "dueLabel": "Wed, Sep 2",
  "outline": "week-02-writing-place/week-02-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154863",
  "title": "ch6",
  "file": "ch6-risk-and-all.pdf",
  "ch": 6,
  "week": 2,
  "day": "Wed",
  "due": "2026-09-02",
  "dueLabel": "Wed, Sep 2",
  "outline": "week-02-writing-place/week-02-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154864",
  "title": "ch7",
  "file": "ch7-seek-surprise.pdf",
  "ch": 7,
  "week": 2,
  "day": "Wed",
  "due": "2026-09-02",
  "dueLabel": "Wed, Sep 2",
  "outline": "week-02-writing-place/week-02-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154865",
  "title": "ch8",
  "file": "ch8-seek-pleasure-in-language.pdf",
  "ch": 8,
  "week": 2,
  "day": "Wed",
  "due": "2026-09-02",
  "dueLabel": "Wed, Sep 2",
  "outline": "week-02-writing-place/week-02-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154866",
  "title": "ch9",
  "file": "ch9-harkening-to-voices.pdf",
  "ch": 9,
  "week": 3,
  "day": "Wed",
  "due": "2026-09-09",
  "dueLabel": "Wed, Sep 9",
  "outline": "week-03-voice-print/week-03-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154843",
  "title": "ch10",
  "file": "ch10-dialog-to-enliven-consolidate-discover.pdf",
  "ch": 10,
  "week": 3,
  "day": "Wed",
  "due": "2026-09-09",
  "dueLabel": "Wed, Sep 9",
  "outline": "week-03-voice-print/week-03-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154844",
  "title": "ch11",
  "file": "ch11-riding-the-rhythm-of-parallel-construction.pdf",
  "ch": 11,
  "week": 4,
  "day": "Mon",
  "due": "2026-09-14",
  "dueLabel": "Mon, Sep 14",
  "outline": "week-04-show-dont-tell/week-04-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154845",
  "title": "ch12",
  "file": "ch12-the-sense-of-it.pdf",
  "ch": 12,
  "week": 4,
  "day": "Mon",
  "due": "2026-09-14",
  "dueLabel": "Mon, Sep 14",
  "outline": "week-04-show-dont-tell/week-04-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154846",
  "title": "ch13",
  "file": "ch13-make-me-taste-it.pdf",
  "ch": 13,
  "week": 4,
  "day": "Mon",
  "due": "2026-09-14",
  "dueLabel": "Mon, Sep 14",
  "outline": "week-04-show-dont-tell/week-04-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154847",
  "title": "ch14",
  "file": "ch14-dramatic-narrative.pdf",
  "ch": 14,
  "week": 5,
  "day": "Mon",
  "due": "2026-09-21",
  "dueLabel": "Mon, Sep 21",
  "outline": "week-05-breaking-the-rules/week-05-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154848",
  "title": "ch15",
  "file": "ch15-break-the-rules-in-style.pdf",
  "ch": 15,
  "week": 5,
  "day": "Mon",
  "due": "2026-09-21",
  "dueLabel": "Mon, Sep 21",
  "outline": "week-05-breaking-the-rules/week-05-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154851",
  "title": "ch18, \"Drawing It Out.\"",
  "file": "ch18-drawing-it-out.pdf",
  "ch": 18,
  "week": 7,
  "day": "Wed",
  "due": "2026-10-07",
  "dueLabel": "Wed, Oct 7",
  "outline": "week-07-regressive-the-scene/week-07-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154849",
  "title": "ch16, \"Metaphor\"",
  "file": "ch16-metaphor-in-your-eye.pdf",
  "ch": 16,
  "week": 9,
  "day": "Mon",
  "due": "2026-10-19",
  "dueLabel": "Mon, Oct 19",
  "outline": "week-09-metaphor-and-leads/week-09-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154850",
  "title": "ch17, \"Leding the Way.\"",
  "file": "ch17-leding-the-way.pdf",
  "ch": 17,
  "week": 9,
  "day": "Mon",
  "due": "2026-10-19",
  "dueLabel": "Mon, Oct 19",
  "outline": "week-09-metaphor-and-leads/week-09-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154852",
  "title": "ch19, \"Mentors, Imitation, and the Like.\"",
  "file": "ch19-mentors-imitation-apprenticeship.pdf",
  "ch": 19,
  "week": 10,
  "day": "Mon",
  "due": "2026-10-26",
  "dueLabel": "Mon, Oct 26",
  "outline": "week-10-mentors-and-the-hinge/week-10-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154854",
  "title": "ch20, \"It Ain't Bourbon Yet.\"",
  "file": "ch20-it-aint-bourbon-yet.pdf",
  "ch": 20,
  "week": 12,
  "day": "Wed",
  "due": "2026-11-11",
  "dueLabel": "Wed, Nov 11",
  "outline": "week-12-sources-into-genres/week-12-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154855",
  "title": "ch21, \"Befriending Revision\"",
  "file": "ch21-befriending-revision.pdf",
  "ch": 21,
  "week": 13,
  "day": "Mon",
  "due": "2026-11-16",
  "dueLabel": "Mon, Nov 16",
  "outline": "week-13-cohere-and-review/week-13-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154856",
  "title": "ch22, \"Dwelling in Your Words.\"",
  "file": "ch22-dwelling-in-your-words.pdf",
  "ch": 22,
  "week": 13,
  "day": "Mon",
  "due": "2026-11-16",
  "dueLabel": "Mon, Nov 16",
  "outline": "week-13-cohere-and-review/week-13-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154857",
  "title": "ch23, \"Revision Illustrated.\"",
  "file": "ch23-revision-illustrated.pdf",
  "ch": 23,
  "week": 13,
  "day": "Wed",
  "due": "2026-11-18",
  "dueLabel": "Wed, Nov 18",
  "outline": "week-13-cohere-and-review/week-13-wed.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154858",
  "title": "ch24, \"Swimming Through Sunlight\"",
  "file": "ch24-swimming-through-sunlight.pdf",
  "ch": 24,
  "week": 15,
  "day": "Mon",
  "due": "2026-11-30",
  "dueLabel": "Mon, Nov 30",
  "outline": "week-15-revise-and-share/week-15-mon.html"
 },
 {
  "kind": "romano",
  "url": "https://miamioh.instructure.com/courses/258319/files/40154859",
  "title": "ch25, \"Faith.\"",
  "file": "ch25-faith.pdf",
  "ch": 25,
  "week": 15,
  "day": "Mon",
  "due": "2026-11-30",
  "dueLabel": "Mon, Nov 30",
  "outline": "week-15-revise-and-share/week-15-mon.html"
 },
 {
  "kind": "currere",
  "url": "https://miamioh.instructure.com/courses/258319/files/40277230",
  "title": "Edwards, \"Who's Cheating Whom?\"",
  "file": "Edwards - Whos Cheating Whom (Currere).pdf",
  "ch": null,
  "week": 1,
  "day": "Wed",
  "due": "2026-08-26",
  "dueLabel": "Wed, Aug 26",
  "outline": "week-01-trust-the-gush/week-01-wed.html"
 },
 {
  "kind": "currere",
  "url": "https://miamioh.instructure.com/courses/258319/files/40277240",
  "title": "Wiederhold, \"How to Read a Blank Page of Writing\"",
  "file": "Wiederhold - How to Read a Blank Page of Writing (Currere).pdf",
  "ch": null,
  "week": 2,
  "day": "Mon",
  "due": "2026-08-31",
  "dueLabel": "Mon, Aug 31",
  "outline": "week-02-writing-place/week-02-mon.html"
 },
 {
  "kind": "currere",
  "url": "https://miamioh.instructure.com/courses/258319/files/40277227",
  "title": "Daspit, \"'None of Us'\"",
  "file": "Daspit - None of Us (Currere).pdf",
  "ch": null,
  "week": 3,
  "day": "Wed",
  "due": "2026-09-09",
  "dueLabel": "Wed, Sep 9",
  "outline": "week-03-voice-print/week-03-wed.html"
 },
 {
  "kind": "currere",
  "url": "https://miamioh.instructure.com/courses/258319/files/40277231",
  "title": "J. Edwards, \"Beyond Presence\"",
  "file": "Edwards J - Beyond Presence (Currere).pdf",
  "ch": null,
  "week": 4,
  "day": "Mon",
  "due": "2026-09-14",
  "dueLabel": "Mon, Sep 14",
  "outline": "week-04-show-dont-tell/week-04-mon.html"
 },
 {
  "kind": "currere",
  "url": "https://miamioh.instructure.com/courses/258319/files/40277236",
  "title": "O'Hara, \"Moviehouse Poems\"",
  "file": "OHara - Moviehouse Poems (Currere).pdf",
  "ch": null,
  "week": 5,
  "day": "Mon",
  "due": "2026-09-21",
  "dueLabel": "Mon, Sep 21",
  "outline": "week-05-breaking-the-rules/week-05-mon.html"
 },
 {
  "kind": "currere",
  "url": "https://miamioh.instructure.com/courses/258319/files/40277234",
  "title": "Moore, \"Starting the Conversation\"",
  "file": "Moore - Starting the Conversation (Currere).pdf",
  "ch": null,
  "week": 6,
  "day": "Mon",
  "due": "2026-09-28",
  "dueLabel": "Mon, Sep 28",
  "outline": "week-06-what-is-currere/week-06-mon.html"
 },
 {
  "kind": "currere",
  "url": "https://miamioh.instructure.com/courses/258319/files/40277239",
  "title": "Romano, \"The Anchor, the Bridge, the Lesson\"",
  "file": "Romano - The Anchor the Bridge the Lesson (Currere).pdf",
  "ch": null,
  "week": 10,
  "day": "Mon",
  "due": "2026-10-26",
  "dueLabel": "Mon, Oct 26",
  "outline": "week-10-mentors-and-the-hinge/week-10-mon.html"
 },
 {
  "kind": "currere",
  "url": "https://miamioh.instructure.com/courses/258319/files/40277226",
  "title": "Bird, \"Self-Coaching Emotions\"",
  "file": "Bird - Self-Coaching Emotions (Currere).pdf",
  "ch": null,
  "week": 10,
  "day": "Mon",
  "due": "2026-10-26",
  "dueLabel": "Mon, Oct 26",
  "outline": "week-10-mentors-and-the-hinge/week-10-mon.html"
 },
 {
  "kind": "article",
  "url": "https://drive.google.com/file/d/1nBnBLC1dJvbwoLGdn6TSG39AvuuRnvl4/view?usp=sharing",
  "title": "\"My Father's Voice\"",
  "file": "",
  "ch": null,
  "week": 3,
  "day": "Wed",
  "due": "2026-09-09",
  "dueLabel": "Wed, Sep 9",
  "outline": "week-03-voice-print/week-03-wed.html"
 },
 {
  "kind": "article",
  "url": "https://www.newyorker.com/tech/annals-of-technology/chatgpt-is-a-blurry-jpeg-of-the-web",
  "title": "Chiang, \"ChatGPT Is a Blurry JPEG of the Web\"",
  "file": "",
  "ch": null,
  "week": 5,
  "day": "Mon",
  "due": "2026-09-21",
  "dueLabel": "Mon, Sep 21",
  "outline": "week-05-breaking-the-rules/week-05-mon.html"
 },
 {
  "kind": "article",
  "url": "https://wrd.as.uky.edu/sites/default/files/1-Shitty%20First%20Drafts.pdf",
  "title": "Lamott, \"Shitty First Drafts\"",
  "file": "",
  "ch": null,
  "week": 5,
  "day": "Mon",
  "due": "2026-09-21",
  "dueLabel": "Mon, Sep 21",
  "outline": "week-05-breaking-the-rules/week-05-mon.html"
 }
];
