// GENERATED by tools/build-tips.py — do not edit by hand.
//
//   python3 tools/build-tips.py ../tce284-fa26
//
// Verbatim passages from Bad Ideas About Writing (Ball & Loewe, WVU Libraries,
// 2017), CC BY-NC-ND 4.0. Attribution travels with every one and none may be
// reworded. Order and vetoes come from tips-chosen.txt.
window.DAILY_TIPS = [
 {
  "date": "2026-08-24",
  "week": 1,
  "day": "Mon",
  "session": "Welcome",
  "text": "The hesitation to write, after all, has been around since we’ve been trying to write. Whenever we stare at a blank page, we’re in good company.",
  "author": "Geoffrey V. Carter",
  "chapter": "Writer’s Block Just Happens to People",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-08-26",
  "week": 1,
  "day": "Wed",
  "session": "Read it, then write it",
  "text": "Publishers present a polished and finalized copy of writing and thereby dilute the messiness of the writing process. The idea that authors derive their writing abilities from their natural intellect is difficult to shake because it is inscribed in the very word author itself.",
  "author": "Dustin Edwards and Enrique Paz",
  "chapter": "Only Geniuses can be Writers",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-08-31",
  "week": 2,
  "day": "Mon",
  "session": "Your Writing Place",
  "text": "What is often neglected in these public debates about the best way to teach literacy … is that reading and writing are connected practices and, as such, the best way to teach them is together. It is a bad idea to continue privileging writing at the expense of reading.",
  "author": "Ellen C. Carillo",
  "chapter": "Reading and Writing are not Connected",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/",
  "elided": true
 },
 {
  "date": "2026-09-02",
  "week": 2,
  "day": "Wed",
  "session": "Build the page",
  "text": "We cannot follow a writing process, because writing is messier than that. Instead, then, revision and process become excuses on the part of writers who have taken a bit too long to finish writing projects, never ending or completing compositional tasks.",
  "author": "Jimmy Butts",
  "chapter": "The More Writing Process, the Better",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-09-09",
  "week": 3,
  "day": "Wed",
  "session": "Voices",
  "text": "Writing fan fiction in Wattpad requires understanding what other fans expect, what fan fiction writers and readers think good fan fiction is, and what the technological medium supports and allows. The same is true for any other kind of writing—we write in our journals and think of our future selves or anyone who might find the journal.",
  "author": "Elizabeth Wardle",
  "chapter": "You Can Learn to Write in General",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-09-14",
  "week": 4,
  "day": "Mon",
  "session": "Show, Don't Tell",
  "text": "No matter how one teaches for transfer, the one consistent recommendation for doing so involves incorporating metacognitive exercises into writing courses. Metacognition literally means thinking about thinking, so metacognitive exercises in the classroom would ask students to think about what they are thinking and learning.",
  "author": "Ellen C. Carillo",
  "chapter": "Writing Knowledge Transfers Easily",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-09-16",
  "week": 4,
  "day": "Wed",
  "session": "Build the moment",
  "text": "Composition scholars readily agree that students need to be taught how to write rather than merely be tasked with writing. So what exactly should reading instruction involve?",
  "author": "Julie Myatt Barger",
  "chapter": "Reading is Not Essential to Writing Instruction",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-09-21",
  "week": 5,
  "day": "Mon",
  "session": "Break the Rules",
  "text": "The belief that writing emerges, Athena-like, fully developed from the writer’s head minimizes both the labor involved and the expectation that writing is a skill that can be improved. But the insidious invisibility of the work of writing perpetuates myths that damage both current and possible writers.",
  "author": "Teri Holbrook and Melanie Hundley",
  "chapter": "Writers are Mythical, Magical, and Damaged",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-09-23",
  "week": 5,
  "day": "Wed",
  "session": "Draft it, flatten it, look back",
  "text": "The most important belief that a writing teacher can have about writing is, as Peter Elbow (a well-known teacher of writing) put it, that everyone can write. And at the heart of that belief is the assumption that everyone’s experience and perspective is already worth writing about as soon they arrive in the classroom.",
  "author": "Ronald Clark Brooks",
  "chapter": "You Need My Credentials to be a Writer",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-09-28",
  "week": 6,
  "day": "Mon",
  "session": "The Currere Begins",
  "text": "In other words, while the idea of the individual author genius is theoretically problematic, it is also practically problematic because our everyday authorship practices are socially situated, collaborative, and interactive. People can and do read and write (and read and write again) all the time.",
  "author": "Jill Parrott",
  "chapter": "Some People are Just Born Good Writers",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-09-30",
  "week": 6,
  "day": "Wed",
  "session": "Currere in the Wild",
  "text": "Currently, the general sentiment is that people should just learn to speak and write proper English. However, over the past several decades, scholars in writing studies have examined the ways in which writing has a close dialectical relationship with identity, style genre, and culture.",
  "author": "Anjali Pattanayak",
  "chapter": "There is One Correct Way of Writing and Speaking",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-10-05",
  "week": 7,
  "day": "Mon",
  "session": "Currere Topic Conferences",
  "text": "All Americans stand to gain by learning to speak, read, and write many languages. Embracing All the Languages of the United States as Gifts The truth is that immigrants to the United States learn English faster today than at any point in history.",
  "author": "Steven Alvarez",
  "chapter": "Official American English is Best",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-10-07",
  "week": 7,
  "day": "Wed",
  "session": "Storyboard Your Scenes",
  "text": "The more writers push through chaos to get to the good stuff, the more they revise. Because writing and revision are impossible to untangle, revision is just as situational and interpretive as writing. In other words, writers interact with readers—writing and revision are social, responsive, and communal.",
  "author": "Laura Giovanelli",
  "chapter": "Strong Writing and Writers Don’t Need Revision",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-10-12",
  "week": 8,
  "day": "Mon",
  "session": "Render the Scenes That Carry the Weight",
  "text": "Reframe the notion of academic writing as a fixed, unchanging, and neutral discourse; think of it instead as a flexible toolkit of language practices that change with the user and the context. Many other literacies that could never conform to a Strunk and White standard continue to enrich ideas of what counts as good writing.",
  "author": "Laura Lisabeth",
  "chapter": "Strunk and White Set the Standard",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-10-14",
  "week": 8,
  "day": "Wed",
  "session": "Break a Rule, Share the Room",
  "text": "By treating the linear model of the writing process as a rule, teachers can create writers who don’t want to and don’t know how to revise as a powerful part of thinking and writing. Think of good writing as the thoughtful use of an evolving repertoire, rather than adherence to a static list of commandments.",
  "author": "Monique Dufour and Jennifer Ahern-Dodson",
  "chapter": "Good Writers Always Follow My Rules",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-10-19",
  "week": 9,
  "day": "Mon",
  "session": "Read It Aloud: Leads & Metaphor",
  "text": "What’s lost by letting go of the myth of the author’s voice? Not much—except, perhaps, a clumsy metaphor that gets in the way of more accurate descriptions of a reader’s response. Conversely, letting go of the author’s voice turns writers’ and writing teachers’ attention toward more important aspects of learning to write.",
  "author": "Patrick Thomas",
  "chapter": "Writers Must Develop a Strong, Original Voice",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-10-21",
  "week": 9,
  "day": "Wed",
  "session": "Currere Draft Conferences",
  "text": "The new rule to adopt is as follows: Speak up and be present and known in your writing! In sum, reliance upon oneself and one’s writing are essential in developing a writing life and an audience. Make your writing and thinking audible on the print and digital page for two: the writer and reader.",
  "author": "Rodrigo Joseph Rodríguez",
  "chapter": "Leave Yourself Out of Your Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-10-26",
  "week": 10,
  "day": "Mon",
  "session": "How a Currere Lands",
  "text": "There are accompanying head nods from classmates that lead to the ideal invitation to discuss why the self matters in everything we write, and why writers bring themselves to the page and screen in their writing. Otherwise, why write at all? Furthermore, why read something that disconnects the writer with hardly any care or concern?",
  "author": "Kimberly N. Parker",
  "chapter": "Response: Never Use “I”",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-10-28",
  "week": 10,
  "day": "Wed",
  "session": "Your Voice, and the Genres Buried Inside",
  "text": "The passive voice is appropriate in some contexts and less so in others, but this is a matter for a writer’s judgment rather than a rule to be (dis)obeyed. We should be teaching writers the skilled application of the passive voice, rather than teaching them to avoid it altogether.",
  "author": "Collin Gifford Brooke",
  "chapter": "The Passive Voice Should be Avoided",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-11-02",
  "week": 11,
  "day": "Mon",
  "session": "Launching the Research Project",
  "text": "To improve writing, find a better way to teach writing. There are good reasons for this advice. Decades of research have shown that isolated grammar exercises are among the worst uses of time in a writing class, given that such practices can result in students’ writing actually getting worse.",
  "author": "Patricia A. Dunn",
  "chapter": "Teaching Grammar Improves Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-11-04",
  "week": 11,
  "day": "Wed",
  "session": "Sources & Setup",
  "text": "Perhaps what has ultimately kept grammar names alive in spite of the research about formal instruction is that writing teachers haven’t much articulated the ways this particular kind of grammar knowledge doesn’t matter. But writing teachers do a disservice, too, if we think we can or should avoid grammar altogether.",
  "author": "Hannah J. Rule",
  "chapter": "Good Writers Must Know Grammatical Terminology",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-11-09",
  "week": 12,
  "day": "Mon",
  "session": "Interrogate & Draft",
  "text": "Extensive meta-studies indicate that teaching grammar rules in isolation is a waste of time; yet, teachers who seem well intentioned continue to teach grammar and test students for mastery. But such definitions are incomplete and totally inadequate for those trying to learn the grammar rules in question.",
  "author": "Muriel Harris",
  "chapter": "Grammar Should be Taught Separately as Rules to Learn",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-11-11",
  "week": 12,
  "day": "Wed",
  "session": "Poem, Image & the First AI Move",
  "text": "Requiring students to create an outline as the first step of the writing process teaches them that writing is a linear movement, when in reality, it’s actually recursive. There’s an age-old argument among those in the composition field. Should teachers and writers be focused on the product or the process of writing?",
  "author": "Kristin Milligan",
  "chapter": "Formal Outlines are Always Useful",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-11-16",
  "week": 13,
  "day": "Mon",
  "session": "Making It One Thing",
  "text": "In place of teaching students to target and purge seemingly faulty reasoning, as was common in his day, Vico advocated teaching what rhetoricians call invention by way of the topics. Invention is the activity of drumming up arguments and is one of the key intellectual practices the discipline of rhetoric offers writers.",
  "author": "Daniel V. Bommarito",
  "chapter": "Students Should Learn About the Logical Fallacies",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-11-18",
  "week": 13,
  "day": "Wed",
  "session": "Read, Respond, Finish the Artifact",
  "text": "Logos, the “argument itself ” according to Aristotle, consists of material such as data and narrative, as well as the cogent reasoning that allows us to make sense of our stories. However, through careless practice, mistranslation, or misconception of the word’s origins, logos is often defined simply as logic.",
  "author": "Nancy Fox",
  "chapter": "Logos is Synonymous with Logic",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-11-30",
  "week": 15,
  "day": "Mon",
  "session": "Revise for the Particular",
  "text": "Humor not only can help teach the elements of writing and thinking while emphasizing collaboration, but it also powerfully makes the case for writing. In this process, invention is true invention: You’re creating something never thought of before. (Unless your essay is about airplane peanuts.",
  "author": "Michael Theune",
  "chapter": "Excellent Academic Writing Must be Serious",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "date": "2026-12-02",
  "week": 15,
  "day": "Wed",
  "session": "The Share-Out",
  "text": "Even more troubling was that when asked if they considered themselves writers, they resoundingly answered no. Even for people who write daily for their trade, writing has become synonymous with poetry and fiction writing, which has become synonymous with creative writing.",
  "author": "Cydney Alexis",
  "chapter": "Creative Writing is a Unique Category",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 }
];
