#!/usr/bin/env python3
"""Assign passages to class meetings and write tips.js.

    python3 tools/passages.py  path/to/badideasaboutwriting-book.pdf   # the pool
    python3 tools/build-tips.py ../tce284-fa26                         # the assignment

tips-chosen.txt names the ones Todd has approved, in order, and vetoes the ones he
has not. Everything it does not cover is filled from the rest of the pool.

⚠ tips-chosen.txt holds POINTERS — a chapter and the first few words. The passage
text is only ever copied from tools/quotes.js, which is only ever copied from the
book. Nothing in this chain retypes a quotation, so no quotation can drift from
what the book actually says. That matters more than usual here: the licence is
CC BY-NC-ND, and a misquotation is both a bad tip and a licence breach.
"""
import re, sys, json, pathlib, importlib.util

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
ARGS = sys.argv[1:]

spec = importlib.util.spec_from_file_location('bp', HERE / 'build-poems.py')
bp = importlib.util.module_from_spec(spec)
sys.argv = ['build-poems.py']
try:
    spec.loader.exec_module(bp)
except SystemExit:
    pass


def pool():
    js = (HERE / 'quotes.js').read_text()
    return json.loads(js[js.index('['):js.rindex(';')])


def wanted():
    f = ROOT / 'tips-chosen.txt'
    keep, veto = [], []
    if not f.exists():
        return keep, veto
    for line in f.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '|' not in line:
            continue
        out = veto if line.startswith('-') else keep
        ch, pre = line.lstrip('-').split('|', 1)
        out.append((ch.strip(), pre.strip()))
    return keep, veto


def norm(t):
    """⚠ The book sets apostrophes curly — "Writer’s Block" — and anything typed
    into tips-chosen.txt by hand will have straight ones. Match without them."""
    return re.sub(r"[‘’']", "'", (t or '')).strip().lower()


def find(qs, ch, pre):
    for q in qs:
        if norm(q['chapter']) == norm(ch) and norm(q['text']).startswith(norm(pre)):
            return q
    return None


def main(course):
    qs = pool()
    keep, veto = wanted()
    dead = {id(find(qs, c, p)) for c, p in veto}
    ordered, used = [], set()
    for c, p in keep:
        q = find(qs, c, p)
        if q:
            ordered.append(q)
            used.add(id(q))
        else:
            print(f'  ! not in the pool: {c} | {p}')
    # ⚠ One passage per chapter before any chapter comes round twice. The pool holds
    # two per chapter and they sit next to each other, so a straight fill put Paul
    # Cook on the 2nd and the 9th and Elizabeth Wardle on the 14th and the 16th.
    rest = [q for q in qs if id(q) not in used and id(q) not in dead]
    seen = {norm(q['chapter']) for q in ordered}
    firsts, seconds = [], []
    for q in rest:
        (seconds if norm(q['chapter']) in seen else firsts).append(q)
        seen.add(norm(q['chapter']))
    ordered += firsts + seconds

    rows = []
    for n, (date, wk, which, path) in enumerate(bp.sessions(pathlib.Path(course).expanduser())):
        if n >= len(ordered):
            break
        q = ordered[n]
        rows.append(dict(date=date.isoformat(), week=wk, day=which,
                         session=bp.session_name(path.read_text()), **q))
        print(f"{date}  {q['chapter'][:44]:46.46} {q['author']}")
    (ROOT / 'tips.js').write_text(
        '// GENERATED by tools/build-tips.py — do not edit by hand.\n'
        '//\n'
        '//   python3 tools/build-tips.py ../tce284-fa26\n'
        '//\n'
        '// Verbatim passages from Bad Ideas About Writing (Ball & Loewe, WVU Libraries,\n'
        '// 2017), CC BY-NC-ND 4.0. Attribution travels with every one and none may be\n'
        '// reworded. Order and vetoes come from tips-chosen.txt.\n'
        'window.DAILY_TIPS = ' + json.dumps(rows, ensure_ascii=False, indent=1) + ';\n')
    print(f'\ntips.js: {len(rows)} class meetings, {len(keep)} chosen by hand, '
          f'{len(veto)} vetoed')


if not ARGS:
    sys.exit(__doc__)
main(ARGS[0])
