#!/usr/bin/env python3
"""Gather the choices, so Todd can make them.

    python3 tools/build-candidates.py ../tce284-fa26
    open tools/curate.html

The builder picks one poem per session on its own. Todd: "Give me a list and I
select some... Could you create a viewer where I quickly move through your
recommended pieces and click use or don't use?" — so this writes every candidate
it would have chosen between, with its full text, and curate.html walks them.

Output is tools/candidates.js, not .json, so curate.html opens from the file
system without a web server.

What comes back out of the curator is a block of lines in the format
poem-substitutes.txt already understands:

    2026-11-04 | Gerard Manley Hopkins | Pied Beauty

Paste it in, re-run build-poems.py, and the picks are pinned. Nothing new to
learn and nothing else to wire up.
"""
import sys, json, pathlib, importlib.util

HERE = pathlib.Path(__file__).resolve().parent
ARGS = sys.argv[1:]                    # ⚠ grabbed BEFORE the import clobbers sys.argv

spec = importlib.util.spec_from_file_location('bp', HERE / 'build-poems.py')
bp = importlib.util.module_from_spec(spec)
sys.argv = ['build-poems.py']          # keep its main() from running on import
try:
    spec.loader.exec_module(bp)
except SystemExit:
    pass


def main(course):
    course = pathlib.Path(course).expanduser().resolve()
    cache = HERE.parent / 'poem-texts' / '_pd'
    pool, pinned = bp.substitutes(HERE.parent)
    out = []
    for date, wk, which, path in bp.sessions(course):
        p = bp.poem(path) or dict(title='', poet='', url='', where='', note='',
                                  text='', textSource='', framing=[])
        p['session'] = bp.session_name(path.read_text())
        cands = []
        # The class poem, when we may print it, is always the first option.
        if p['text']:
            cands.append(dict(poet=p['poet'], title=p['title'], text=p['text'],
                              lines=len(p['text'].splitlines()),
                              textSource=p['textSource'], why='the class poem itself'))
        cands += bp.candidates(p, cache)
        # Then the curated list, so there is always something to fall back to.
        for author, title in pool:
            if any(c['poet'] == author and c['title'] == title for c in cands):
                continue
            text, note = bp.poetrydb(author, title, cache)
            if text:
                cands.append(dict(poet=author, title=title, text=text,
                                  lines=len(text.splitlines()), textSource=note,
                                  why='from the list'))
        out.append(dict(date=date.isoformat(), week=wk, day=which,
                        session=p['session'], classPoem=p['title'], classPoet=p['poet'],
                        pinned='%s | %s' % pinned[date.isoformat()] if date.isoformat() in pinned else '',
                        candidates=cands))
        print(f"{date}  {p['title'] or '(' + p['session'] + ')'}  —  {len(cands)} to choose from")
    js = HERE / 'candidates.js'
    js.write_text('// GENERATED by tools/build-candidates.py — input for curate.html\n'
                  'window.CANDIDATES = ' + json.dumps(out, ensure_ascii=False, indent=1) + ';\n')
    print(f'\n{js}: {len(out)} sessions, '
          f'{sum(len(o["candidates"]) for o in out)} candidates')


if not ARGS:
    sys.exit(__doc__)
main(ARGS[0])
