#!/usr/bin/env python3
"""Short passages from Bad Ideas About Writing, attributed by POSITION.

    python3 tools/passages.py path/to/badideasaboutwriting-book.pdf

⚠ The first version of this matched each chapter title in the body text and sliced
between the matches. It put "Revision is not a sign of weakness" under "Official
American English is Best" and served up several Further Reading lists and author
bios as though they were the argument. Under a BY licence a wrong attribution is
the one unacceptable bug, so nothing is attributed by slicing any more.

Instead: every chapter is anchored on its author's name printed under its title,
the body ends where "Further Reading" begins, and a passage is only ever reported
with the chapter it physically sits inside.

ND: passages are verbatim runs of whole consecutive sentences. Nothing is reworded,
nothing is stitched across a gap.
"""
import re, sys, subprocess, json, pathlib

BAD = re.compile(r'\(\s*\d{4}|et al|http|www\.|\bsee (also |especially )?[A-Z]|\d\d', re.I)
LEAD = re.compile(r'^(But|And|So|Yet|Or|Nor|Thus|Then|However|Instead|Moreover|Therefore|'
                  r'This|That|These|Those|It|They|He|She|Such|Another|Worse|'
                  r'In (this|that|the (first|second|next|last))|For (this|that|them)|'
                  r'As (such|a result))\b', re.I)
WANT = re.compile(r'\b(writ|revis|draft|reader|read|sentence|word|voice|grammar|'
                  r'process|failur|mistake|practice|page|think|learn|teach|story)', re.I)


def toc(text):
    out, lines = [], text.splitlines()
    for i, ln in enumerate(lines[:400]):
        m = re.match(r'^\s*(.+?)\s{2,}(\d{1,3})\s*$', ln)
        if not m:
            continue
        t = m.group(1).strip()
        if len(t) < 12 or t.isupper() or t.lower().startswith('introduction'):
            continue
        nxt = lines[i + 1].strip() if i + 1 < len(lines) else ''
        if not nxt or re.search(r'\d\s*$', nxt) or len(nxt) > 60 or nxt.isupper():
            continue
        out.append((t, nxt))
    return out


def bodies(text, entries):
    """[(start, end, title, author)] — anchored on the byline, cut at Further Reading."""
    spans = []
    for title, author in entries:
        # The byline is printed under the chapter title; the TOC copy is far earlier.
        for m in re.finditer(r'^\s*%s\s*$' % re.escape(author), text, re.M):
            if m.start() < len(text) * 0.06:
                continue
            head = text[max(0, m.start() - 400):m.start()]
            if re.sub(r'[^A-Z]', '', head[-300:]).count(
                    re.sub(r'[^A-Z]', '', title.upper())[:10]) or \
               re.sub(r'[^A-Z]', '', title.upper())[:10] in re.sub(r'[^A-Z]', '', head):
                spans.append((m.end(), title, author))
                break
    spans.sort()
    out = []
    for n, (pos, title, author) in enumerate(spans):
        stop = len(text) if n + 1 == len(spans) else spans[n + 1][0]
        chunk = text[pos:stop]
        cut = re.search(r'\n\s*Further Reading\s*\n', chunk)
        out.append((chunk[:cut.start()] if cut else chunk, title, author))
    return out


def passages(body):
    b = re.sub(r'-\s*\n', '', body)
    b = re.sub(r'\n\s*\d{1,3}\s+Bad Ideas\s*\n', ' ', b)      # running footer
    b = re.sub(r'\s+', ' ', b)
    ss = [x.strip() for x in re.split(r'(?<=[.?!])\s+(?=[A-Z“"])', b)]
    ss = [x for x in ss if 25 < len(x) < 230]
    for i in range(1, max(1, len(ss) - 2)):
        for n in (2, 3):
            w = ss[i:i + n]
            if len(w) < n:
                continue
            t = ' '.join(w)
            if not (140 <= len(t) <= 340) or not t.endswith(('.', '?', '!')):
                continue
            if BAD.search(t) or LEAD.search(w[0]) or re.search(r'\bI\b|\bmy\b', t):
                continue
            if len(WANT.findall(t)) < 2:
                continue
            yield (len(WANT.findall(t)) * 3 - len(t) / 70, t)


def main(pdf):
    text = subprocess.run(['pdftotext', '-layout', str(pdf), '-'],
                          capture_output=True, text=True, check=True).stdout
    out = []
    for body, title, author in bodies(text, toc(text)):
        # Four per chapter, not two. Todd wants more from Elizabeth Wardle — she
        # teaches at Miami, where this course runs — and a favoured author is only
        # as deep as the pool. More candidates also means more for the curator to
        # choose between, which is the point of it.
        best = sorted(passages(body), reverse=True)[:4]
        for score, t in best:
            out.append(dict(text=t, author=author, chapter=title,
                            book='Bad Ideas About Writing, ed. Ball & Loewe '
                                 '(WVU Libraries, 2017), CC BY-NC-ND 4.0',
                            url='https://textbooks.lib.wvu.edu/badideas/'))
    js = pathlib.Path(__file__).resolve().parent / 'quotes.js'
    js.write_text('// GENERATED by tools/passages.py — input for curate.html\n'
                  '// Verbatim passages from a CC BY-NC-ND text. Attribution travels with\n'
                  '// each one and nothing here may be reworded. See the script header.\n'
                  'window.QUOTES = ' + json.dumps(out, ensure_ascii=False, indent=1) + ';\n')
    for q in out:
        print(f"{q['text']}\n    -- {q['author']}, “{q['chapter']}”\n")
    print(f'{js}: {len(out)} passages')


if len(sys.argv) < 2:
    sys.exit(__doc__)
main(sys.argv[1])
