// GENERATED by tools/passages.py — input for curate.html
// Verbatim passages from a CC BY-NC-ND text. Attribution travels with
// each one and nothing here may be reworded. See the script header.
window.QUOTES = [
 {
  "text": "Writing, in other words, embraces much more than relaying a preset message to a reader. FYC is uniquely qualified to provide this experience for several reasons. Students in FYC, whether in face-to-face (f2f) or online sections, benefit from the interactions they have with other writers, texts, and their teachers.",
  "author": "Paul G. Cook",
  "chapter": "First-Year Composition Should be Skipped",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Second, writing is a curious and ancient technology. Our familiarity with writing and with the many important tasks it performs— from texting to Twitter—leads people to assume that writing is a basic skill they’ve already learned if not mastered.",
  "author": "Paul G. Cook",
  "chapter": "First-Year Composition Should be Skipped",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The idea that we can all learn to “write in general” is not just a harmless myth. It’s a dangerous idea that needs to die because it hurts students and frustrates teachers and employers. And writers who believe it are easily discouraged because they don’t know how to learn what they need to learn in new writing situations.",
  "author": "Elizabeth Wardle",
  "chapter": "You Can Learn to Write in General",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Writing fan fiction in Wattpad requires understanding what other fans expect, what fan fiction writers and readers think good fan fiction is, and what the technological medium supports and allows. The same is true for any other kind of writing—we write in our journals and think of our future selves or anyone who might find the journal.",
  "author": "Elizabeth Wardle",
  "chapter": "You Can Learn to Write in General",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "No matter how one teaches for transfer, the one consistent recommendation for doing so involves incorporating metacognitive exercises into writing courses. Metacognition literally means thinking about thinking, so metacognitive exercises in the classroom would ask students to think about what they are thinking and learning.",
  "author": "Ellen C. Carillo",
  "chapter": "Writing Knowledge Transfers Easily",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Curricula must be redesigned with the concept of transfer in mind, and instructors must be trained to teach toward the goal of transfer. No matter how one teaches for transfer, the one consistent recommendation for doing so involves incorporating metacognitive exercises into writing courses.",
  "author": "Ellen C. Carillo",
  "chapter": "Writing Knowledge Transfers Easily",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "What is often neglected in these public debates about the best way to teach literacy at the college level is that reading and writing are connected practices and, as such, the best way to teach them is together. It is a bad idea to continue privileging writing at the expense of reading.",
  "author": "Ellen C. Carillo",
  "chapter": "Reading and Writing are not Connected",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "A better understanding of this as a reader can also support students’ writing as they develop their own arguments. Instructors might also provide a strategy such as reading like a writer, wherein readers notice the choices a writer has made and understands the relevance of those choices to their own writing.",
  "author": "Ellen C. Carillo",
  "chapter": "Reading and Writing are not Connected",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Composition scholars readily agree that students need to be taught how to write rather than merely be tasked with writing. So what exactly should reading instruction involve?",
  "author": "Julie Myatt Barger",
  "chapter": "Reading is Not Essential to Writing Instruction",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Distancing the composition classroom from literature left reading out in the cold, resulting in less attention to reading instruction in the FYC classroom. Third, there is a lack of recent research on reading in the field of composition studies and a gap in teacher training, particularly at the university level.",
  "author": "Julie Myatt Barger",
  "chapter": "Reading is Not Essential to Writing Instruction",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The belief that writing emerges, Athena-like, fully developed from the writer’s head minimizes both the labor involved and the expectation that writing is a skill that can be improved. But the insidious invisibility of the work of writing perpetuates myths that damage both current and possible writers.",
  "author": "Teri Holbrook and Melanie Hundley",
  "chapter": "Writers are Mythical, Magical, and Damaged",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "After all, given these kinds of on-the-job hazards, who would ever aspire to the writing life? Popular Portrait #1: Writers Possess Magical Gifts This view of writers supports the idea that since writing is magical, it isn’t work.",
  "author": "Teri Holbrook and Melanie Hundley",
  "chapter": "Writers are Mythical, Magical, and Damaged",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Is it something unique to the craft of writing and the anxieties it provokes? Is this an anxiety one sees from the practitioners of all underappreciated arts? The most important belief that a writing teacher can have about writing is, as Peter Elbow (a well-known teacher of writing) put it, that everyone can write.",
  "author": "Ronald Clark Brooks",
  "chapter": "You Need My Credentials to be a Writer",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The most important belief that a writing teacher can have about writing is, as Peter Elbow (a well-known teacher of writing) put it, that everyone can write. And at the heart of that belief is the assumption that everyone’s experience and perspective is already worth writing about as soon they arrive in the classroom.",
  "author": "Ronald Clark Brooks",
  "chapter": "You Need My Credentials to be a Writer",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Publishers present a polished and finalized copy of writing and thereby dilute the messiness of the writing process. The idea that authors derive their writing abilities from their natural intellect is difficult to shake because it is inscribed in the very word author itself.",
  "author": "Dustin Edwards and Enrique Paz",
  "chapter": "Only Geniuses can be Writers",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "In other words, instead of the reclusive genius, we aim to be social writers. Instead of inspiration from within, we seek influence from without. Writing requires talking to friends, asking help from colleagues, finding answers and ideas in others’ writings, and indulging in those practices.",
  "author": "Dustin Edwards and Enrique Paz",
  "chapter": "Only Geniuses can be Writers",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "In other words, while the idea of the individual author genius is theoretically problematic, it is also practically problematic because our everyday authorship practices are socially situated, collaborative, and interactive. People can and do read and write (and read and write again) all the time.",
  "author": "Jill Parrott",
  "chapter": "Some People are Just Born Good Writers",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "People can and do read and write (and read and write again) all the time. Social media such as Twitter, Facebook, Instagram, and others offer daily opportunities for reading, creating, and responding to texts.",
  "author": "Jill Parrott",
  "chapter": "Some People are Just Born Good Writers",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Failure in writing betrays dullness of mind, smallness of imagination. The failed writer—the one who cannot learn to write well (which is to say, according to accepted conventions of good writing)—is discounted as dim, unprepared, non-serious, wacky, or weird, distracted, behind. Or, failure is acceptable if we learn from it.",
  "author": "Allison D. Carr",
  "chapter": "Failure is Not an Option",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The failed writer—the one who cannot learn to write well (which is to say, according to accepted conventions of good writing)—is discounted as dim, unprepared, non-serious, wacky, or weird, distracted, behind. Or, failure is acceptable if we learn from it.",
  "author": "Allison D. Carr",
  "chapter": "Failure is Not an Option",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Currently, the general sentiment is that people should just learn to speak and write proper English. However, over the past several decades, scholars in writing studies have examined the ways in which writing has a close dialectical relationship with identity, style genre, and culture.",
  "author": "Anjali Pattanayak",
  "chapter": "There is One Correct Way of Writing and Speaking",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "David Gold highlights the marginalization of women, working class, rural, and African American literacy in our understanding of writing. Gold writes about how the literacy practices of African Americans in universities laid the groundwork for the Civil Rights movement.",
  "author": "Anjali Pattanayak",
  "chapter": "There is One Correct Way of Writing and Speaking",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "There is also a construction that includes the word be known as habitual be, meaning that if the word be is used in a sentence, an action is consistent or regular. Therefore, She be reading means, in Standard American English, She reads all of the time.",
  "author": "Jennifer M. Cunningham",
  "chapter": "African American Language is not Good English",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Both are correct linguistically. There is also a construction that includes the word be known as habitual be, meaning that if the word be is used in a sentence, an action is consistent or regular. Therefore, She be reading means, in Standard American English, She reads all of the time.",
  "author": "Jennifer M. Cunningham",
  "chapter": "African American Language is not Good English",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "All Americans stand to gain by learning to speak, read, and write many languages. Embracing All the Languages of the United States as Gifts The truth is that immigrants to the United States learn English faster today than at any point in history.",
  "author": "Steven Alvarez",
  "chapter": "Official American English is Best",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The real limit for all students is mainstreaming policy that cuts away at the plurilingual gifts of our nation. All Americans stand to gain by learning to speak, read, and write many languages.",
  "author": "Steven Alvarez",
  "chapter": "Official American English is Best",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The hesitation to write, after all, has been around since we’ve been trying to write. Whenever we stare at a blank page, we’re in good company.",
  "author": "Geoffrey V. Carter",
  "chapter": "Writer’s Block Just Happens to People",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Upper’s failure.” Who knew that it would be serious business to publish a blank page in an academic journal that, at the time, had been publishing for over half a century? The humor of this article often causes people to smile.",
  "author": "Geoffrey V. Carter",
  "chapter": "Writer’s Block Just Happens to People",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The more writers push through chaos to get to the good stuff, the more they revise. Because writing and revision are impossible to untangle, revision is just as situational and interpretive as writing. In other words, writers interact with readers—writing and revision are social, responsive, and communal.",
  "author": "Laura Giovanelli",
  "chapter": "Strong Writing and Writers Don’t Need Revision",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "In Stephen King’s memoir On Writing, he calls this instinct the ideal reader: an imagined person a writer knows and trusts but rewrites in response to, a kind of collaborative dance between writer and reader. To writers, the act of writing is an act of thinking. Revision is not a sign of weakness or inexperienced or poor writing.",
  "author": "Laura Giovanelli",
  "chapter": "Strong Writing and Writers Don’t Need Revision",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "We cannot follow a writing process, because writing is messier than that. Instead, then, revision and process become excuses on the part of writers who have taken a bit too long to finish writing projects, never ending or completing compositional tasks.",
  "author": "Jimmy Butts",
  "chapter": "The More Writing Process, the Better",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Most post-process critiques of the process formula suggest that a process view is invalid by merely embracing more complex, unknowable processes. Of course, the idea of following a formula to write a perfect draft is a false construction. We write for specific situations, each unique.",
  "author": "Jimmy Butts",
  "chapter": "The More Writing Process, the Better",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Reframe the notion of academic writing as a fixed, unchanging, and neutral discourse; think of it instead as a flexible toolkit of language practices that change with the user and the context. Many other literacies that could never conform to a Strunk and White standard continue to enrich ideas of what counts as good writing.",
  "author": "Laura Lisabeth",
  "chapter": "Strunk and White Set the Standard",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "White, is well loved by many writers and teachers as the ultimate reference book on Standard English. Ask any writer or editor, and they are likely to have one of its four editions on their bookshelves or will remember it from some phase of their education.",
  "author": "Laura Lisabeth",
  "chapter": "Strunk and White Set the Standard",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "By treating the linear model of the writing process as a rule, teachers can create writers who don’t want to and don’t know how to revise as a powerful part of thinking and writing. Think of good writing as the thoughtful use of an evolving repertoire, rather than adherence to a static list of commandments.",
  "author": "Monique Dufour and Jennifer Ahern-Dodson",
  "chapter": "Good Writers Always Follow My Rules",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "For example, that linear model of the writing process can be very effective—it might work for a writer for virtually every email, report, and research project she writes, year after year. Perhaps she’s writing a long, complex project such as a dissertation or a book.",
  "author": "Monique Dufour and Jennifer Ahern-Dodson",
  "chapter": "Good Writers Always Follow My Rules",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "What’s lost by letting go of the myth of the author’s voice? Not much—except, perhaps, a clumsy metaphor that gets in the way of more accurate descriptions of a reader’s response. Conversely, letting go of the author’s voice turns writers’ and writing teachers’ attention toward more important aspects of learning to write.",
  "author": "Patrick Thomas",
  "chapter": "Writers Must Develop a Strong, Original Voice",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Not much—except, perhaps, a clumsy metaphor that gets in the way of more accurate descriptions of a reader’s response. Conversely, letting go of the author’s voice turns writers’ and writing teachers’ attention toward more important aspects of learning to write.",
  "author": "Patrick Thomas",
  "chapter": "Writers Must Develop a Strong, Original Voice",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The new rule to adopt is as follows: Speak up and be present and known in your writing! In sum, reliance upon oneself and one’s writing are essential in developing a writing life and an audience. Make your writing and thinking audible on the print and digital page for two: the writer and reader.",
  "author": "Rodrigo Joseph Rodríguez",
  "chapter": "Leave Yourself Out of Your Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "In sum, reliance upon oneself and one’s writing are essential in developing a writing life and an audience. Make your writing and thinking audible on the print and digital page for two: the writer and reader.",
  "author": "Rodrigo Joseph Rodríguez",
  "chapter": "Leave Yourself Out of Your Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "There are accompanying head nods from classmates that lead to the ideal invitation to discuss why the self matters in everything we write, and why writers bring themselves to the page and screen in their writing. Otherwise, why write at all? Furthermore, why read something that disconnects the writer with hardly any care or concern?",
  "author": "Kimberly N. Parker",
  "chapter": "Response: Never Use “I”",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Otherwise, why write at all? Furthermore, why read something that disconnects the writer with hardly any care or concern? Again, young writers can be skeptical of this pushback, since they’ve perfected being disconnected from their own writing and human voice.",
  "author": "Kimberly N. Parker",
  "chapter": "Response: Never Use “I”",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The passive voice is appropriate in some contexts and less so in others, but this is a matter for a writer’s judgment rather than a rule to be (dis)obeyed. We should be teaching writers the skilled application of the passive voice, rather than teaching them to avoid it altogether.",
  "author": "Collin Gifford Brooke",
  "chapter": "The Passive Voice Should be Avoided",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Outside of Twitter, though, we do not write in single sentences. Our prose is much more likely to happen in paragraphs and pages, and the passive voice plays an important role here as well. Williams argues in Style: Lessons in Clarity and Grace that readable prose is more than simply finding the best sentence in each case.",
  "author": "Collin Gifford Brooke",
  "chapter": "The Passive Voice Should be Avoided",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "To improve writing, find a better way to teach writing. There are good reasons for this advice. Decades of research have shown that isolated grammar exercises are among the worst uses of time in a writing class, given that such practices can result in students’ writing actually getting worse.",
  "author": "Patricia A. Dunn",
  "chapter": "Teaching Grammar Improves Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "One way to improve writing is to stop looking for a better way to teach grammar. To improve writing, find a better way to teach writing. There are good reasons for this advice.",
  "author": "Patricia A. Dunn",
  "chapter": "Teaching Grammar Improves Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Perhaps what has ultimately kept grammar names alive in spite of the research about formal instruction is that writing teachers haven’t much articulated the ways this particular kind of grammar knowledge doesn’t matter. But writing teachers do a disservice, too, if we think we can or should avoid grammar altogether.",
  "author": "Hannah J. Rule",
  "chapter": "Good Writers Must Know Grammatical Terminology",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "A better idea about writing is rather that good writers know how to do grammar to myriad effects. Dunn puts it, students must develop their grammar and sentence chops through engagement in writing they care about, not through the estrangement of decontextualized drills and memorization.",
  "author": "Hannah J. Rule",
  "chapter": "Good Writers Must Know Grammatical Terminology",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Extensive meta-studies indicate that teaching grammar rules in isolation is a waste of time; yet, teachers who seem well intentioned continue to teach grammar and test students for mastery. But such definitions are incomplete and totally inadequate for those trying to learn the grammar rules in question.",
  "author": "Muriel Harris",
  "chapter": "Grammar Should be Taught Separately as Rules to Learn",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The obvious conclusion—that we understand the concept of sentences as expressing complete thoughts—apparently didn’t help these students correctly identify word groups that were complete thoughts. But the students who weren’t able to identify which word groups were sentences no doubt had written vast numbers of sentences of their own.",
  "author": "Muriel Harris",
  "chapter": "Grammar Should be Taught Separately as Rules to Learn",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Requiring students to create an outline as the first step of the writing process teaches them that writing is a linear movement, when in reality, it’s actually recursive. There’s an age-old argument among those in the composition field. Should teachers and writers be focused on the product or the process of writing?",
  "author": "Kristin Milligan",
  "chapter": "Formal Outlines are Always Useful",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Should teachers and writers be focused on the product or the process of writing? Writing can be understood in a variety of ways, but one consistent factor is the idea of planning before actually writing the intended piece.",
  "author": "Kristin Milligan",
  "chapter": "Formal Outlines are Always Useful",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "In place of teaching students to target and purge seemingly faulty reasoning, as was common in his day, Vico advocated teaching what rhetoricians call invention by way of the topics. Invention is the activity of drumming up arguments and is one of the key intellectual practices the discipline of rhetoric offers writers.",
  "author": "Daniel V. Bommarito",
  "chapter": "Students Should Learn About the Logical Fallacies",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Invention is the activity of drumming up arguments and is one of the key intellectual practices the discipline of rhetoric offers writers. The topics were helpful forms of reasoning that offered people strategies for producing arguments in a variety of contexts.",
  "author": "Daniel V. Bommarito",
  "chapter": "Students Should Learn About the Logical Fallacies",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Logos, the “argument itself ” according to Aristotle, consists of material such as data and narrative, as well as the cogent reasoning that allows us to make sense of our stories. However, through careless practice, mistranslation, or misconception of the word’s origins, logos is often defined simply as logic.",
  "author": "Nancy Fox",
  "chapter": "Logos is Synonymous with Logic",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Humor not only can help teach the elements of writing and thinking while emphasizing collaboration, but it also powerfully makes the case for writing. In this process, invention is true invention: You’re creating something never thought of before. (Unless your essay is about airplane peanuts.",
  "author": "Michael Theune",
  "chapter": "Excellent Academic Writing Must be Serious",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "In comedy, it’s not word choice, but the hunt for the choicest word. And sentences must be tightly woven to serve as the fuse that carries the spark right to an ending that blows readers away.",
  "author": "Michael Theune",
  "chapter": "Excellent Academic Writing Must be Serious",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Even more troubling was that when asked if they considered themselves writers, they resoundingly answered no. Even for people who write daily for their trade, writing has become synonymous with poetry and fiction writing, which has become synonymous with creative writing.",
  "author": "Cydney Alexis",
  "chapter": "Creative Writing is a Unique Category",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "How did the field of creative writing, and the public’s idea about this type of writing, emerge? In The Elephants Teach, D.G. Mearns developed and popularized what’s considered to be the first creative writing workshop for junior high school students.",
  "author": "Cydney Alexis",
  "chapter": "Creative Writing is a Unique Category",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "First-year writing courses are often regarded as providing the single inoculation for writing—and against popular culture—that students need. Instead, we must understand that writing and reading are abilities that we acquire through learning and practice, and that we never stop learning them.",
  "author": "Bronwyn T. Williams",
  "chapter": "Popular Culture is Killing Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Although there are other modes of communication online, such as video, there is still a tremendous amount of reading and writing taking place in online spaces. In fact, compared with thirty years ago, when television and film dominated popular culture practices, young people today are engaged in significantly more reading and writing.",
  "author": "Bronwyn T. Williams",
  "chapter": "Popular Culture is Killing Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Students can write ethnographic research reports on face-to-face or digital communities that chart the movement of writing practices within a network of fan activity. Fan fiction can be analyzed (and even compared to the original work) as an exercise in learning style and voice.",
  "author": "Mark D. Pepper",
  "chapter": "Popular Culture is Only Useful as a Text for Criticism",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Fandom writing also brings a myriad of possibilities to the classroom. Students can write ethnographic research reports on face-to-face or digital communities that chart the movement of writing practices within a network of fan activity.",
  "author": "Mark D. Pepper",
  "chapter": "Popular Culture is Only Useful as a Text for Criticism",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Most college writing instructors have eschewed the 5PE, contending that it limits what writing can be, constricts writers’ roles, and even arbitrarily shapes writers’ thoughts. Yet, defenders of the 5PE counter that beginning writers need the guidance and structure that it affords.",
  "author": "Quentin Vieregge",
  "chapter": "The Five-Paragraph Essay is Rhetorically Sound",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Each topic sentence is followed by sentences that provide evidence and reinforce the thesis. The body paragraphs end with a wrap-up sentence. The conclusion reminds the reader of the main idea, summarizes the main points, and might even leave the reader with one lasting impression.",
  "author": "Quentin Vieregge",
  "chapter": "The Five-Paragraph Essay is Rhetorically Sound",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "When students are challenged to write beyond memorized formulas, to travel beyond the how of writing to the why of writing, they learn skills of academic resiliency that will transfer to college and beyond. Freire also addresses this.",
  "author": "Susan Naomi Bernstein and Elizabeth Lowry",
  "chapter": "The Five-Paragraph Essay Transmits Knowledge",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Anyone who interrogated this standard method for writing, whether teacher or student, need not apply. After the essay-writing test ended, the applicants met for a short break and discussed with one another the essays they had just written.",
  "author": "Susan Naomi Bernstein and Elizabeth Lowry",
  "chapter": "The Five-Paragraph Essay Transmits Knowledge",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The manner in which we assess writing will always exert a tremendous influence over how we teach writing. Over the last two decades, we have consistently been fed a lie that teacher evaluation is biased; as a result, standardized testing is necessary to hold schools accountable for student learning.",
  "author": "Bruce Bowles, Jr.",
  "chapter": "The Five-Paragraph Theme Teaches “Beyond the Test”",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Writing portfolios would enable local educators to assess how students perform on a multitude of writing tasks across a variety of contexts. Electronic portfolios would even allow students to practice technological literacy skills.",
  "author": "Bruce Bowles, Jr.",
  "chapter": "The Five-Paragraph Theme Teaches “Beyond the Test”",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The use of the research paper proliferated until it became the primary genre students write—a genre less about creating knowledge and more about compiling it. Subsequently, the research paper became a tool for teaching students how to use the library, find the right words, and skillfully search through the words of others.",
  "author": "Alison C. Witte",
  "chapter": "Research Starts with Answers",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Perhaps some of the confusion over the role of research in writing, and the writing process, comes from the structure of classical argument that is often included as part of the organizational pattern for the research paper. When argument is taught, it’s frequently connected to the historical practices of Greek and Roman rhetoric.",
  "author": "Alison C. Witte",
  "chapter": "Research Starts with Answers",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "In the book, A Writing Process, author Vinetta Bell suggests that the thesis-writing process begins during the “preliminary research” stage. This strategy is endorsed by multiple research library websites, such as the University of Minnesota.",
  "author": "Emily A. Wierszewski",
  "chapter": "Research Starts with a Thesis Statement",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "How could something be changed for the better? When we understand research as a process of discovery rather than a process of proof, we open ourselves up to be changed by our research—to better our lives, our decisions, and our world.",
  "author": "Emily A. Wierszewski",
  "chapter": "Research Starts with a Thesis Statement",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Too often this simplistic approach is mistaken for laziness. But, most people cannot handle the chore of deciphering the data deluge. Plagiarism, then, becomes a major effect of the Internet’s causal effect on teaching and learning the research paper.",
  "author": "Alexandria Lockett",
  "chapter": "The Traditional Research Paper is Best",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "At best, research papers 2.0 will encourage students and instructors to reflect on how the Internet and its complex networked features mediate their research and writing process. Specifically, research 2.0 might include a much stronger emphasis on collaborative and professional writing.",
  "author": "Alexandria Lockett",
  "chapter": "The Traditional Research Paper is Best",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Outside of school, there are many ways to convey credibility and indicate relationships to the sources used for a piece. Writing with authority is complicated and needs to be learned anew in each situation: successful writing isn’t just about following rules, but about establishing connections among readers and writers.",
  "author": "Susanmarie Harrington",
  "chapter": "Citing Sources is a Basic Skill Learned Early On",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Citing sources in very particular and detailed ways allows readers to find any source material the writer used, and allows readers to evaluate the quality of the source material the writer used. But complex citation systems have other purposes as well: They let writers demonstrate strong command of highly specialized work.",
  "author": "Susanmarie Harrington",
  "chapter": "Citing Sources is a Basic Skill Learned Early On",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Second, writers who are learning a new field often try out ideas and phrases from other writers in order to master the field. This process allows them to learn, and is a far cry from stealing.",
  "author": "Jennifer A. Mott-Smith",
  "chapter": "Plagiarism Deserves to be Punished",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "When we read, we always bring our own knowledge to what we’re reading. Writers cannot say everything; they have to rely on the readers to supply their side of the meaning making. One difficulty arises when you read an argument with missing steps.",
  "author": "Jennifer A. Mott-Smith",
  "chapter": "Plagiarism Deserves to be Punished",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "For example, in English classes, teachers would respond to student writing in both written and spoken form. There were many levels of communication between the student and teacher, which provided more opportunity for the student to gain an understanding and command of course content.",
  "author": "Mitchell R. James",
  "chapter": "Grading Has Always Made Writing Better",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "In addition, formative evaluation creates safe spaces for student learning because students are not focused on trying to avoid failure but, instead, are searching for insight and growth. As grades lose their power, the desire to evade punishment or failure can dissolve into the desire to seek knowledge and learn something new.",
  "author": "Mitchell R. James",
  "chapter": "Grading Has Always Made Writing Better",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Patricia Cross, the top teaching goals for English are writing skills, think[ing] for oneself, and analytic skills. The arts, humanities, and English share think for oneself as a high-priority goal. In other words, the most important goals for writing teachers are among the most difficult to evaluate.",
  "author": "Anne Leahy",
  "chapter": "Rubrics Save Time and Make Grading Criteria Visible",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Students know that, on some level, they are writing to the rubric, instead of writing to think. Another contemporary definition of the word is as a heading or category. That definition suggests that using a rubric to evaluate writing is a way to label a piece of writing (and, perhaps unintentionally, label the writer as well).",
  "author": "Anne Leahy",
  "chapter": "Rubrics Save Time and Make Grading Criteria Visible",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "A paradigm shift that explores a balance between rubrics as a part of writing assessment, and the realities of the teaching loads of many writing faculty would be most beneficial to our field. The reality that there are elements of writing that rubrics of any reasonable length cannot capture should not be ignored.",
  "author": "Crystal Sands",
  "chapter": "Rubrics Oversimplify the Writing Process",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "We deserve at least part of a weekend off. A paradigm shift that explores a balance between rubrics as a part of writing assessment, and the realities of the teaching loads of many writing faculty would be most beneficial to our field.",
  "author": "Crystal Sands",
  "chapter": "Rubrics Oversimplify the Writing Process",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Although extensive commenting on student writing is not a universal practice, it is widespread, widely accepted, and widely practiced. Moreover, if writing comments and questions on the paper has educational value, then for many teachers, even more written response results in even more learning.",
  "author": "Muriel Harris",
  "chapter": "When Responding to Student Writing, More is Better",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Teachers who spend extensive time writing on student papers are apparently convinced that students learn from their responses. Parents and administrators are happy because they too assume that more teacher verbiage results in more learning—with a corollary that an exceptional teacher therefore offers extensive feedback.",
  "author": "Muriel Harris",
  "chapter": "When Responding to Student Writing, More is Better",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The teacher’s view of student writing is but one voice among a chorus of peers. Writing benefits from collaboration, not top-down dictatorship. Learning to write means learning to write with the support of peers, in an authentic situation, and with a genuine purpose.",
  "author": "Christopher R. Friend",
  "chapter": "Student Writing Must be Graded by the Teacher",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Learning about situations and the effects of writing comes from reading and writing, not from being graded. Students should learn to assess writing situations and learn how to improve that writing—both theirs and their peers’—in situations that have more at stake than just a grade.",
  "author": "Christopher R. Friend",
  "chapter": "Student Writing Must be Graded by the Teacher",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "When we speak or write, large amounts of information are left out and inferred by the listener or reader. When we read, “Fred realized he couldn’t pay for his daughter’s tuition. He looked up his uncle’s email address,” the space between the two sentences is filled with information that we infer.",
  "author": "Chris M. Anson and Les Perelman",
  "chapter": "Machines can Evaluate Writing Well",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Writing is far more complex than a missing comma. The testing agencies that fail to understand fully what writing is and how the ability to produce it is best measured are at fault. Taking the Machine Out of Writing Assessment When it comes to testing and evaluating our kids’ writing, machines alone aren’t really the problem.",
  "author": "Chris M. Anson and Les Perelman",
  "chapter": "Machines can Evaluate Writing Well",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Maybe John, since he seems to never be paying attention. Or maybe Kim, since she doesn’t write all that well. Or what about Bob, because his essay was so well written?",
  "author": "Stephanie Vie",
  "chapter": "Plagiarism Detection Services are Money Well Spent",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Initially, plagiarism detection technologies like Turnitin.com or Blackboard’s SafeAssign sound like ideal solutions. These technologies promise to detect how much writing is unoriginal in a piece, allowing the viewer of one of their originality reports to assess the level of potential plagiarism in a written document.",
  "author": "Stephanie Vie",
  "chapter": "Plagiarism Detection Services are Money Well Spent",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Likewise, if everyone studies and practices for the test and all perform well, they all receive licenses. The purpose of a writing placement test is to determine which course within a specific program best matches a student’s writing strengths and weaknesses.",
  "author": "Kristen di Gennaro",
  "chapter": "SAT Scores are Useful for Placing Students in Writing Courses",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Less clear are cases where different tests adopt a similar format, such as the SAT writing component and a college writing placement test. The SAT is a norm-referenced test.",
  "author": "Kristen di Gennaro",
  "chapter": "SAT Scores are Useful for Placing Students in Writing Courses",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "We need to put to rest the idea that digital forms of writing pose a threat to overall writing ability. In particular, we must address claims of specific cause-and-effect between digital writing and bad grammar.",
  "author": "Scott Warnock",
  "chapter": "Texting Ruins Students’ Grammar Skills",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "An unstated implication of these beliefs might be that digital writing is harming the next generation’s ability to think clearly. We need to put to rest the idea that digital forms of writing pose a threat to overall writing ability.",
  "author": "Scott Warnock",
  "chapter": "Texting Ruins Students’ Grammar Skills",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Because writing and speech are radically different, the two should be distinguished. However, McWhorter argues that as writing—a far more recent phenomena than speech—advanced, some speech emulated writing, but some writing also emulated speech.",
  "author": "Christopher Justice",
  "chapter": "Texting Ruins Literacy Skills",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Because writing and speech are radically different, the two should be distinguished. However, McWhorter argues that as writing—a far more recent phenomena than speech—advanced, some speech emulated writing, but some writing also emulated speech. That’s where texting first emerged.",
  "author": "Christopher Justice",
  "chapter": "Texting Ruins Literacy Skills",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "To embrace the paradox buried in that interplay is to make writing fun. Writing can and will be fun when it invites and makes possible opportunities for play. Because writing situations provide writers with familiar rules and conventions, writers have the opportunity to move within and through those forms to create and strategize.",
  "author": "Joshua Daniel-Wariya",
  "chapter": "Gamification Makes Writing Fun",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Writing can and will be fun when it invites and makes possible opportunities for play. Because writing situations provide writers with familiar rules and conventions, writers have the opportunity to move within and through those forms to create and strategize.",
  "author": "Joshua Daniel-Wariya",
  "chapter": "Gamification Makes Writing Fun",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "All students—not just writing students—need to be taught how to be effective users of a range of composing technologies. Writing teachers “need to inhabit an ecology that supports their efforts over time,” say Richard J. Selfe, writing and technology experts.",
  "author": "Genesea M. Carter and Aurora Matzke",
  "chapter": "The More Digital Technology, the Better",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Beliefs about technologies have changed the way we think about and understand the entire enterprise of writing education. Furthermore, what if emphasizing the technologies that students find familiar and engaging in the writing classroom actually hinders learning?",
  "author": "Genesea M. Carter and Aurora Matzke",
  "chapter": "The More Digital Technology, the Better",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "We have to understand that as technology changes, culture also changes, and as writers we have to think about how audiences change and how composing practices change across time. This is a difficult and nuanced, an always changing and complex practice. We must always think about the words we use to speak about important concepts.",
  "author": "Phill Michael Alexander",
  "chapter": "Digital Natives and Digital Immigrants",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "We have to understand that as technology changes, culture also changes, and as writers we have to think about how audiences change and how composing practices change across time. This is a difficult and nuanced, an always changing and complex practice.",
  "author": "Phill Michael Alexander",
  "chapter": "Digital Natives and Digital Immigrants",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "What we teach, however, does have larger implications. Sometimes it is the skill or concept, and sometimes the reach is about helping students learn how to learn, and how to enjoy or value their education.",
  "author": "Andrew Hollinger",
  "chapter": "You’re Going to Need This for College",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "What is problematic is to suggest that anyone not participating in the system is less for doing so. What we teach, however, does have larger implications. Sometimes it is the skill or concept, and sometimes the reach is about helping students learn how to learn, and how to enjoy or value their education.",
  "author": "Andrew Hollinger",
  "chapter": "You’re Going to Need This for College",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "College composition courses usually focus on writing as a process so that a student will go through the actions of drafting and revising one or more texts throughout the semester. This drafting and revision process functions well in the college environment, where class times can be flexible.",
  "author": "Caroline Wilkinson",
  "chapter": "Dual-Enrollment Writing Classes Should Always be Pursued",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "A college instructor or high-school instructor will teach it. The constant is that high-school students will be involved. College composition courses usually focus on writing as a process so that a student will go through the actions of drafting and revising one or more texts throughout the semester.",
  "author": "Caroline Wilkinson",
  "chapter": "Dual-Enrollment Writing Classes Should Always be Pursued",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Online writing courses can be successful at promoting writing skills, but only if the instructor re-envisions her pedagogical practices. Indeed, we would argue that f2f writing instructors can learn from online pedagogy.",
  "author": "Tiffany Bourelle and Andy Bourelle",
  "chapter": "Face-to-Face Courses are Superior to Online Courses",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "If an instructor isn’t active in the course, the students may put in little effort as well. Online writing courses can be successful at promoting writing skills, but only if the instructor re-envisions her pedagogical practices. Indeed, we would argue that f2f writing instructors can learn from online pedagogy.",
  "author": "Tiffany Bourelle and Andy Bourelle",
  "chapter": "Face-to-Face Courses are Superior to Online Courses",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Students learn to write by having opportunities to read, think, write, reflect, receive feedback, and write again. Someone who teaches writing in any discipline should be a good writing teacher with abundant knowledge and what might be called a full toolbox of literacy skills and abilities.",
  "author": "Beth L. Hewett",
  "chapter": "Anyone Can Teach an Online Writing Course",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "Online writing-intensive courses therefore force students to read content, instructions, peer writing and comments, and teacher feedback; in other words, they get to read a lot. Online writing courses also enable students to write much more than in traditional on-site courses.",
  "author": "Beth L. Hewett",
  "chapter": "Anyone Can Teach an Online Writing Course",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The key word is professional. The people teaching college writing courses have graduate degrees, often more than one— many have spent years on the job. Many conduct research into effective teaching or do other kinds of research that help them teach writing.",
  "author": "Seth Kahn",
  "chapter": "Anyone Can Teach Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 },
 {
  "text": "The people teaching college writing courses have graduate degrees, often more than one— many have spent years on the job. Many conduct research into effective teaching or do other kinds of research that help them teach writing.",
  "author": "Seth Kahn",
  "chapter": "Anyone Can Teach Writing",
  "book": "Bad Ideas About Writing, ed. Ball & Loewe (WVU Libraries, 2017), CC BY-NC-ND 4.0",
  "url": "https://textbooks.lib.wvu.edu/badideas/"
 }
];
